# Big Mac Activities
Let's take a look at a familiar data set (the cost of big macs around the world) and analyse it using Jupyter Notebook and Pandas. This skillset will **_directly_** link to your assessment task.

Complete each activity stipulated in the comments by looking at the *even-more-python-for-beginners* provided on GitHub.

## Series
Complete the following pandas Series following the instructions in the comments:

In [49]:
import pandas as pd

countries = pd.Series([
                        'Australia',
                        'Britain',
                        'New Zealand',
                        'United States'
                        ])
countries


#Create a pandas Series which contains 'Australia', 'Britain', 'New Zealand' and 'United States' and store them on separate lines in a variable, 'countries'. 
#Print the series

0        Australia
1          Britain
2      New Zealand
3    United States
dtype: str

In [61]:
#Output Britain from the list using its index
countries[1]

'Britain'

In [72]:
#Iterate through all values in countries series using a for loop
for x in countries:
    print(x)

Australia
Britain
New Zealand
United States

## DataFrame
Usually we work with two-dimensional arrays. We store them using **DataFrame** in pandas. 

### Activity
Let's use a DataFrame to store more meaningful values than our countries series. Let's store the following values in a Data Frame called 'big_mac':

**Headings:** Country, Local Price, AUD Price
- `'Australia', 7.45, 7.45`
- `'Britain', 4.19, 0.0`
- `'Japan', 450, 0.0`
- `'New Zealand', 7.1, 0.0`
- `'United States', 5.58, 0.0`

**NOTE:** You'll need to look online at current rates to convert Britain, New Zealand, Japan and United States' local prices to AUD.

In [93]:
#Add a pandas DataFrame called 'big_mac' with the above values
big_mac = pd.DataFrame([
                        ['Australia', 7.45, 7.45],
                        ['Britain', 4.19, 0.0],
                        ['Japan', 450, 0.0],
                        ['New Zealand', 7.1, 0.0],
                        ['United States', 5.58, 0.0],
                        ],
                        columns = ['Country', 'Local Price', 'AUD Price']
                        )
#Print the DataFrame
big_mac

         Country  Local Price  AUD Price
0      Australia         7.45       7.45
1        Britain         4.19       0.00
2          Japan       450.00       0.00
3    New Zealand         7.10       0.00
4  United States         5.58       0.00

## Examining pandas DataFrames

In [156]:

big_mac.head(2)

     Country  Local Price  AUD Price
0  Australia         7.45       7.45
1    Britain         4.19       0.00

In [173]:
#Print only the last four rows of the big_mac dataframe
big_mac.tail(4)

         Country  Local Price  AUD Price
1        Britain         4.19        0.0
2          Japan       450.00        0.0
3    New Zealand         7.10        0.0
4  United States         5.58        0.0

In [180]:
#Print the number of rows and columns in the big_mac dataframe
big_mac.shape

(5, 3)

In [186]:
#Print some detailed information about the big_mac dataframe
big_mac.info

<bound method DataFrame.info of          Country  Local Price  AUD Price
0      Australia         7.45       7.45
1        Britain         4.19       0.00
2          Japan       450.00       0.00
3    New Zealand         7.10       0.00
4  United States         5.58       0.00>

## Querying DataFrames
Let's explore how we request data from a pandas DataFrame.

In [225]:
#Request and output the 'Country' and 'AUD Price' columns from the big_mac DataFrame.
big_mac[['Country', 'AUD Price']]

         Country  AUD Price
0      Australia       7.45
1        Britain       0.00
2          Japan       0.00
3    New Zealand       0.00
4  United States       0.00

In [ ]:
#Use iloc to request the third row, all columns

IndexingError: Too many indexers

In [ ]:
#Use iloc to request all rows, but just the 'Country' and 'AUD Price' columns

In [ ]:
#Use loc to do the same thing as the previous (Country and AUD Price all rows)